import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import  NavbarDemo  from "@/components/navbar";
import { Toaster } from "sonner";
import Footer from "@/components/footer";
import { AuthProvider } from '@/context/authContext';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark bg-[#FAF0E6] bg-cover`}
        style={{ backgroundImage: "url('/bg-img.jpeg')" }}
      >
        
       <NavbarDemo/>
       <AuthProvider>{children}</AuthProvider>
        <Toaster richColors position="bottom-right"/>
      </body>
      <Footer />
    </html>
  );
}
